### ISSUE TITLE
VideoOSD

### ISSUE THREAD

**Issue by lzoubek** [scarfa/skin.rapier#2]
Hi, your skin looks awesome! Pretty simple and fast on my box. I just saw you are getting it into official repo :)

What I miss (in most of skins though) is what Neon skin has. When you play the video, it shows current time, video length and also **what time it will be when you finish the movie**. Would you be so kind to add this feature?

Thanks

Libor

**Comment by scarfa** [comment]
Thanks! 

Finish time is shown on the seek bar and current time can be seen by pulling up video info (i on keyboard).

**Comment by lzoubek** [comment]
Oh, sorry the time is there. Cool. I saw some time values there and didn't realize it's my time, since my eden version is showing UTC, but I am UTC+2. I was just telling to myself: what the hell are these numbers about :-)

Thanks
