### ISSUE TITLE
Can't move anywhere after cancelling favorite

### ISSUE THREAD

**Issue by clodeindustrie** [scarfa/skin.rapier#23]
Hi,

I'm using the last Rapier on my ATV2 pre-eden XBMC I noticed that if from the home page I make the favorites window appear and press menu to cancel it. I find myself back on the home page but unable to do anything as nothing seems to be selected/highlighted and clicking on any other button of the remote control doesn't change anything. The only thing I can do is make the favorites window appear again by pressing menu.

Cheers,
Jeremy

**Comment by scarfa** [comment]
This only happens in home? I added cancel buttons to favourites dialog. Let me know if that helps.

**Comment by clodeindustrie** [comment]
I haven't been using xbmc extensively yet but that's the only place it happened as far as I know. I'll update my version and see if it helps.

Cheers
